// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateRelationSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateRelationRequest struct {
	RelationWrite *shared.RelationWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

type CreateRelation422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// CreateRelation422ApplicationJSON - Invalid data posted
type CreateRelation422ApplicationJSON struct {
	Errors  []CreateRelation422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                  `json:"message,omitempty"`
}

// CreateRelation403ApplicationJSON - Forbidden
type CreateRelation403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateRelation401ApplicationJSON - Unauthenticated
type CreateRelation401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateRelation201ApplicationJSON - Created
type CreateRelation201ApplicationJSON struct {
	Data *shared.RelationRead `json:"data,omitempty"`
}

type CreateRelationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateRelation201ApplicationJSONObject *CreateRelation201ApplicationJSON
	// Unauthenticated
	CreateRelation401ApplicationJSONObject *CreateRelation401ApplicationJSON
	// Forbidden
	CreateRelation403ApplicationJSONObject *CreateRelation403ApplicationJSON
	// Invalid data posted
	CreateRelation422ApplicationJSONObject *CreateRelation422ApplicationJSON
}
