// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateRelationRequest struct {
	RelationWrite *shared.RelationWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *CreateRelationRequest) GetRelationWrite() *shared.RelationWrite {
	if o == nil {
		return nil
	}
	return o.RelationWrite
}

func (o *CreateRelationRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

// CreateRelationResponseBody - Created
type CreateRelationResponseBody struct {
	Data *shared.RelationRead `json:"data,omitempty"`
}

func (o *CreateRelationResponseBody) GetData() *shared.RelationRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateRelationResponse struct {
	// Created
	TwoHundredAndOneApplicationJSONObject *CreateRelationResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateRelationResponse) GetTwoHundredAndOneApplicationJSONObject() *CreateRelationResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndOneApplicationJSONObject
}

func (o *CreateRelationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateRelationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateRelationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
