// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateDepartmentRequest struct {
	DepartmentWrite *shared.DepartmentWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *CreateDepartmentRequest) GetDepartmentWrite() *shared.DepartmentWrite {
	if o == nil {
		return nil
	}
	return o.DepartmentWrite
}

func (o *CreateDepartmentRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

// CreateDepartmentResponseBody - Created
type CreateDepartmentResponseBody struct {
	Data *shared.DepartmentRead `json:"data,omitempty"`
}

func (o *CreateDepartmentResponseBody) GetData() *shared.DepartmentRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateDepartmentResponse struct {
	// Created
	TwoHundredAndOneApplicationJSONObject *CreateDepartmentResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateDepartmentResponse) GetTwoHundredAndOneApplicationJSONObject() *CreateDepartmentResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndOneApplicationJSONObject
}

func (o *CreateDepartmentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateDepartmentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateDepartmentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
