// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateContractRequest struct {
	ContractWrite *shared.ContractWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *CreateContractRequest) GetContractWrite() *shared.ContractWrite {
	if o == nil {
		return nil
	}
	return o.ContractWrite
}

func (o *CreateContractRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

// CreateContractResponseBody - Created
type CreateContractResponseBody struct {
	Data *shared.ContractRead `json:"data,omitempty"`
}

func (o *CreateContractResponseBody) GetData() *shared.ContractRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateContractResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created
	Object *CreateContractResponseBody
}

func (o *CreateContractResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateContractResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateContractResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateContractResponse) GetObject() *CreateContractResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
