// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateOfficeRequest struct {
	OfficeWrite *shared.OfficeWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *CreateOfficeRequest) GetOfficeWrite() *shared.OfficeWrite {
	if o == nil {
		return nil
	}
	return o.OfficeWrite
}

func (o *CreateOfficeRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

// CreateOfficeResponseBody - Created
type CreateOfficeResponseBody struct {
	Data *shared.OfficeRead `json:"data,omitempty"`
}

func (o *CreateOfficeResponseBody) GetData() *shared.OfficeRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateOfficeResponse struct {
	// Created
	TwoHundredAndOneApplicationJSONObject *CreateOfficeResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateOfficeResponse) GetTwoHundredAndOneApplicationJSONObject() *CreateOfficeResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndOneApplicationJSONObject
}

func (o *CreateOfficeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateOfficeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateOfficeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
