// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateContractSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateContractRequest struct {
	ContractWrite *shared.ContractWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

type CreateContract422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// CreateContract422ApplicationJSON - Invalid data posted
type CreateContract422ApplicationJSON struct {
	Errors  []CreateContract422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                  `json:"message,omitempty"`
}

// CreateContract403ApplicationJSON - Forbidden
type CreateContract403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateContract401ApplicationJSON - Unauthenticated
type CreateContract401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateContract201ApplicationJSON - Created
type CreateContract201ApplicationJSON struct {
	Data *shared.ContractRead `json:"data,omitempty"`
}

type CreateContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateContract201ApplicationJSONObject *CreateContract201ApplicationJSON
	// Unauthenticated
	CreateContract401ApplicationJSONObject *CreateContract401ApplicationJSON
	// Forbidden
	CreateContract403ApplicationJSONObject *CreateContract403ApplicationJSON
	// Invalid data posted
	CreateContract422ApplicationJSONObject *CreateContract422ApplicationJSON
}
