// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateTaskRequest struct {
	TaskWrite *shared.TaskWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *CreateTaskRequest) GetTaskWrite() *shared.TaskWrite {
	if o == nil {
		return nil
	}
	return o.TaskWrite
}

func (o *CreateTaskRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

// CreateTaskResponseBody - OK
type CreateTaskResponseBody struct {
	Data *shared.TaskRead `json:"data,omitempty"`
}

func (o *CreateTaskResponseBody) GetData() *shared.TaskRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateTaskResponse struct {
	// OK
	TwoHundredApplicationJSONObject *CreateTaskResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateTaskResponse) GetTwoHundredApplicationJSONObject() *CreateTaskResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *CreateTaskResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateTaskResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateTaskResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
