// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateOfficeSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateOfficeRequest struct {
	OfficeWrite *shared.OfficeWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

type CreateOffice422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// CreateOffice422ApplicationJSON - Invalid data posted
type CreateOffice422ApplicationJSON struct {
	Errors  []CreateOffice422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                `json:"message,omitempty"`
}

// CreateOffice403ApplicationJSON - Forbidden
type CreateOffice403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateOffice401ApplicationJSON - Unauthenticated
type CreateOffice401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateOffice201ApplicationJSON - Created
type CreateOffice201ApplicationJSON struct {
	Data *shared.OfficeRead `json:"data,omitempty"`
}

type CreateOfficeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateOffice201ApplicationJSONObject *CreateOffice201ApplicationJSON
	// Unauthenticated
	CreateOffice401ApplicationJSONObject *CreateOffice401ApplicationJSON
	// Forbidden
	CreateOffice403ApplicationJSONObject *CreateOffice403ApplicationJSON
	// Invalid data posted
	CreateOffice422ApplicationJSONObject *CreateOffice422ApplicationJSON
}
