// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type CreateDepartmentSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateDepartmentRequest struct {
	DepartmentWrite *shared.DepartmentWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

type CreateDepartment422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// CreateDepartment422ApplicationJSON - Invalid data posted
type CreateDepartment422ApplicationJSON struct {
	Errors  []CreateDepartment422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                    `json:"message,omitempty"`
}

// CreateDepartment403ApplicationJSON - Forbidden
type CreateDepartment403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateDepartment401ApplicationJSON - Unauthenticated
type CreateDepartment401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// CreateDepartment201ApplicationJSON - Created
type CreateDepartment201ApplicationJSON struct {
	Data *shared.DepartmentRead `json:"data,omitempty"`
}

type CreateDepartmentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateDepartment201ApplicationJSONObject *CreateDepartment201ApplicationJSON
	// Unauthenticated
	CreateDepartment401ApplicationJSONObject *CreateDepartment401ApplicationJSON
	// Forbidden
	CreateDepartment403ApplicationJSONObject *CreateDepartment403ApplicationJSON
	// Invalid data posted
	CreateDepartment422ApplicationJSONObject *CreateDepartment422ApplicationJSON
}
