// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOfficeRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the office
	Office int64 `pathParam:"style=simple,explode=false,name=office"`
}

func (o *DeleteOfficeRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *DeleteOfficeRequest) GetOffice() int64 {
	if o == nil {
		return 0
	}
	return o.Office
}

type DeleteOfficeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteOfficeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteOfficeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteOfficeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
