// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteRelationSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type DeleteRelationRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the relation
	Relation int64 `pathParam:"style=simple,explode=false,name=relation"`
}

// DeleteRelation404ApplicationJSON - Not Found
type DeleteRelation404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteRelation403ApplicationJSON - Forbidden
type DeleteRelation403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteRelation401ApplicationJSON - Unauthenticated
type DeleteRelation401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteRelation400ApplicationJSON - Precondition failed
type DeleteRelation400ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type DeleteRelationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Precondition failed
	DeleteRelation400ApplicationJSONObject *DeleteRelation400ApplicationJSON
	// Unauthenticated
	DeleteRelation401ApplicationJSONObject *DeleteRelation401ApplicationJSON
	// Forbidden
	DeleteRelation403ApplicationJSONObject *DeleteRelation403ApplicationJSON
	// Not Found
	DeleteRelation404ApplicationJSONObject *DeleteRelation404ApplicationJSON
}
