// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteContractSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type DeleteContractRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the contract
	Contract int64 `pathParam:"style=simple,explode=false,name=contract"`
}

// DeleteContract404ApplicationJSON - Not Found
type DeleteContract404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteContract403ApplicationJSON - Forbidden
type DeleteContract403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteContract401ApplicationJSON - Unauthenticated
type DeleteContract401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteContract400ApplicationJSON - Precondition failed
type DeleteContract400ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type DeleteContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Precondition failed
	DeleteContract400ApplicationJSONObject *DeleteContract400ApplicationJSON
	// Unauthenticated
	DeleteContract401ApplicationJSONObject *DeleteContract401ApplicationJSON
	// Forbidden
	DeleteContract403ApplicationJSONObject *DeleteContract403ApplicationJSON
	// Not Found
	DeleteContract404ApplicationJSONObject *DeleteContract404ApplicationJSON
}
