// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteDocumentRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the document
	Document int64 `pathParam:"style=simple,explode=false,name=document"`
}

func (o *DeleteDocumentRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *DeleteDocumentRequest) GetDocument() int64 {
	if o == nil {
		return 0
	}
	return o.Document
}

type DeleteDocument422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

func (o *DeleteDocument422ApplicationJSONErrors) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *DeleteDocument422ApplicationJSONErrors) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

// DeleteDocument422ApplicationJSON - Invalid data posted
type DeleteDocument422ApplicationJSON struct {
	Errors  []DeleteDocument422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                  `json:"message,omitempty"`
}

func (o *DeleteDocument422ApplicationJSON) GetErrors() []DeleteDocument422ApplicationJSONErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *DeleteDocument422ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// DeleteDocument404ApplicationJSON - Not Found
type DeleteDocument404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteDocument404ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// DeleteDocument403ApplicationJSON - Forbidden
type DeleteDocument403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteDocument403ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// DeleteDocument401ApplicationJSON - Unauthenticated
type DeleteDocument401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteDocument401ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type DeleteDocumentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Unauthenticated
	DeleteDocument401ApplicationJSONObject *DeleteDocument401ApplicationJSON
	// Forbidden
	DeleteDocument403ApplicationJSONObject *DeleteDocument403ApplicationJSON
	// Not Found
	DeleteDocument404ApplicationJSONObject *DeleteDocument404ApplicationJSON
	// Invalid data posted
	DeleteDocument422ApplicationJSONObject *DeleteDocument422ApplicationJSON
}

func (o *DeleteDocumentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteDocumentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteDocumentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteDocumentResponse) GetDeleteDocument401ApplicationJSONObject() *DeleteDocument401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteDocument401ApplicationJSONObject
}

func (o *DeleteDocumentResponse) GetDeleteDocument403ApplicationJSONObject() *DeleteDocument403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteDocument403ApplicationJSONObject
}

func (o *DeleteDocumentResponse) GetDeleteDocument404ApplicationJSONObject() *DeleteDocument404ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteDocument404ApplicationJSONObject
}

func (o *DeleteDocumentResponse) GetDeleteDocument422ApplicationJSONObject() *DeleteDocument422ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteDocument422ApplicationJSONObject
}
