// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOfficeSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type DeleteOfficeRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the office
	Office int64 `pathParam:"style=simple,explode=false,name=office"`
}

// DeleteOffice404ApplicationJSON - Not Found
type DeleteOffice404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteOffice403ApplicationJSON - Forbidden
type DeleteOffice403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteOffice401ApplicationJSON - Unauthenticated
type DeleteOffice401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteOffice400ApplicationJSON - Precondition failed
type DeleteOffice400ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type DeleteOfficeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Precondition failed
	DeleteOffice400ApplicationJSONObject *DeleteOffice400ApplicationJSON
	// Unauthenticated
	DeleteOffice401ApplicationJSONObject *DeleteOffice401ApplicationJSON
	// Forbidden
	DeleteOffice403ApplicationJSONObject *DeleteOffice403ApplicationJSON
	// Not Found
	DeleteOffice404ApplicationJSONObject *DeleteOffice404ApplicationJSON
}
