// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteContractRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the contract
	Contract int64 `pathParam:"style=simple,explode=false,name=contract"`
}

func (o *DeleteContractRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *DeleteContractRequest) GetContract() int64 {
	if o == nil {
		return 0
	}
	return o.Contract
}

// DeleteContract404ApplicationJSON - Not Found
type DeleteContract404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteContract404ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// DeleteContract403ApplicationJSON - Forbidden
type DeleteContract403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteContract403ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// DeleteContract401ApplicationJSON - Unauthenticated
type DeleteContract401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteContract401ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// DeleteContract400ApplicationJSON - Precondition failed
type DeleteContract400ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteContract400ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type DeleteContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Precondition failed
	DeleteContract400ApplicationJSONObject *DeleteContract400ApplicationJSON
	// Unauthenticated
	DeleteContract401ApplicationJSONObject *DeleteContract401ApplicationJSON
	// Forbidden
	DeleteContract403ApplicationJSONObject *DeleteContract403ApplicationJSON
	// Not Found
	DeleteContract404ApplicationJSONObject *DeleteContract404ApplicationJSON
}

func (o *DeleteContractResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteContractResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteContractResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteContractResponse) GetDeleteContract400ApplicationJSONObject() *DeleteContract400ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteContract400ApplicationJSONObject
}

func (o *DeleteContractResponse) GetDeleteContract401ApplicationJSONObject() *DeleteContract401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteContract401ApplicationJSONObject
}

func (o *DeleteContractResponse) GetDeleteContract403ApplicationJSONObject() *DeleteContract403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteContract403ApplicationJSONObject
}

func (o *DeleteContractResponse) GetDeleteContract404ApplicationJSONObject() *DeleteContract404ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DeleteContract404ApplicationJSONObject
}
