// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteDepartmentSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type DeleteDepartmentRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the department
	Department int64 `pathParam:"style=simple,explode=false,name=department"`
}

// DeleteDepartment404ApplicationJSON - Not Found
type DeleteDepartment404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteDepartment403ApplicationJSON - Forbidden
type DeleteDepartment403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteDepartment401ApplicationJSON - Unauthenticated
type DeleteDepartment401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteDepartment400ApplicationJSON - Precondition failed
type DeleteDepartment400ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type DeleteDepartmentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Precondition failed
	DeleteDepartment400ApplicationJSONObject *DeleteDepartment400ApplicationJSON
	// Unauthenticated
	DeleteDepartment401ApplicationJSONObject *DeleteDepartment401ApplicationJSON
	// Forbidden
	DeleteDepartment403ApplicationJSONObject *DeleteDepartment403ApplicationJSON
	// Not Found
	DeleteDepartment404ApplicationJSONObject *DeleteDepartment404ApplicationJSON
}
