// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteDocumentSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type DeleteDocumentRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the document
	Document int64 `pathParam:"style=simple,explode=false,name=document"`
}

type DeleteDocument422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// DeleteDocument422ApplicationJSON - Invalid data posted
type DeleteDocument422ApplicationJSON struct {
	Errors  []DeleteDocument422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                  `json:"message,omitempty"`
}

// DeleteDocument404ApplicationJSON - Not Found
type DeleteDocument404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteDocument403ApplicationJSON - Forbidden
type DeleteDocument403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// DeleteDocument401ApplicationJSON - Unauthenticated
type DeleteDocument401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type DeleteDocumentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Unauthenticated
	DeleteDocument401ApplicationJSONObject *DeleteDocument401ApplicationJSON
	// Forbidden
	DeleteDocument403ApplicationJSONObject *DeleteDocument403ApplicationJSON
	// Not Found
	DeleteDocument404ApplicationJSONObject *DeleteDocument404ApplicationJSON
	// Invalid data posted
	DeleteDocument422ApplicationJSONObject *DeleteDocument422ApplicationJSON
}
