// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type GetContractSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetContractRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the contract
	Contract int64 `pathParam:"style=simple,explode=false,name=contract"`
}

// GetContract404ApplicationJSON - Not Found
type GetContract404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetContract403ApplicationJSON - Forbidden
type GetContract403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetContract401ApplicationJSON - Unauthenticated
type GetContract401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetContract200ApplicationJSON - OK
type GetContract200ApplicationJSON struct {
	Data *shared.ContractRead `json:"data,omitempty"`
}

type GetContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetContract200ApplicationJSONObject *GetContract200ApplicationJSON
	// Unauthenticated
	GetContract401ApplicationJSONObject *GetContract401ApplicationJSON
	// Forbidden
	GetContract403ApplicationJSONObject *GetContract403ApplicationJSON
	// Not Found
	GetContract404ApplicationJSONObject *GetContract404ApplicationJSON
}
