// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type GetDepartmentSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetDepartmentRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the department
	Department int64 `pathParam:"style=simple,explode=false,name=department"`
}

// GetDepartment404ApplicationJSON - Not Found
type GetDepartment404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetDepartment403ApplicationJSON - Forbidden
type GetDepartment403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetDepartment401ApplicationJSON - Unauthenticated
type GetDepartment401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetDepartment200ApplicationJSON - OK
type GetDepartment200ApplicationJSON struct {
	Data *shared.DepartmentRead `json:"data,omitempty"`
}

type GetDepartmentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetDepartment200ApplicationJSONObject *GetDepartment200ApplicationJSON
	// Unauthenticated
	GetDepartment401ApplicationJSONObject *GetDepartment401ApplicationJSON
	// Forbidden
	GetDepartment403ApplicationJSONObject *GetDepartment403ApplicationJSON
	// Not Found
	GetDepartment404ApplicationJSONObject *GetDepartment404ApplicationJSON
}
