// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type GetDepartmentRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the department
	Department int64 `pathParam:"style=simple,explode=false,name=department"`
}

func (o *GetDepartmentRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *GetDepartmentRequest) GetDepartment() int64 {
	if o == nil {
		return 0
	}
	return o.Department
}

// GetDepartmentResponseBody - OK
type GetDepartmentResponseBody struct {
	Data *shared.DepartmentRead `json:"data,omitempty"`
}

func (o *GetDepartmentResponseBody) GetData() *shared.DepartmentRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetDepartmentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *GetDepartmentResponseBody
}

func (o *GetDepartmentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetDepartmentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetDepartmentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetDepartmentResponse) GetObject() *GetDepartmentResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
