// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type GetRelationSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetRelationRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the relation
	Relation int64 `pathParam:"style=simple,explode=false,name=relation"`
}

// GetRelation404ApplicationJSON - Not Found
type GetRelation404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetRelation403ApplicationJSON - Forbidden
type GetRelation403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetRelation401ApplicationJSON - Unauthenticated
type GetRelation401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetRelation200ApplicationJSON - OK
type GetRelation200ApplicationJSON struct {
	Data *shared.RelationRead `json:"data,omitempty"`
}

type GetRelationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetRelation200ApplicationJSONObject *GetRelation200ApplicationJSON
	// Unauthenticated
	GetRelation401ApplicationJSONObject *GetRelation401ApplicationJSON
	// Forbidden
	GetRelation403ApplicationJSONObject *GetRelation403ApplicationJSON
	// Not Found
	GetRelation404ApplicationJSONObject *GetRelation404ApplicationJSON
}
