// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type GetTaskRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the task
	Task int64 `pathParam:"style=simple,explode=false,name=task"`
}

func (o *GetTaskRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *GetTaskRequest) GetTask() int64 {
	if o == nil {
		return 0
	}
	return o.Task
}

// GetTaskResponseBody - OK
type GetTaskResponseBody struct {
	Data *shared.TaskRead `json:"data,omitempty"`
}

func (o *GetTaskResponseBody) GetData() *shared.TaskRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetTaskResponse struct {
	// OK
	TwoHundredApplicationJSONObject *GetTaskResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetTaskResponse) GetTwoHundredApplicationJSONObject() *GetTaskResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *GetTaskResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTaskResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTaskResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
