// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListOfficesSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ListOfficesRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

// ListOffices403ApplicationJSON - Forbidden
type ListOffices403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// ListOffices401ApplicationJSON - Unauthenticated
type ListOffices401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type ListOfficesResponse struct {
	ContentType string
	// OK
	OfficeCollection *shared.OfficeCollection
	StatusCode       int
	RawResponse      *http.Response
	// Unauthenticated
	ListOffices401ApplicationJSONObject *ListOffices401ApplicationJSON
	// Forbidden
	ListOffices403ApplicationJSONObject *ListOffices403ApplicationJSON
}
