// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListTasksRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// The page to retrieve
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
}

func (o *ListTasksRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *ListTasksRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

type ListTasksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TaskCollection *shared.TaskCollection
}

func (o *ListTasksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListTasksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListTasksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListTasksResponse) GetTaskCollection() *shared.TaskCollection {
	if o == nil {
		return nil
	}
	return o.TaskCollection
}
