// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListTasksRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// The page to retrieve
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
}

func (o *ListTasksRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *ListTasksRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

// ListTasks403ApplicationJSON - Forbidden
type ListTasks403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *ListTasks403ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// ListTasks401ApplicationJSON - Unauthenticated
type ListTasks401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *ListTasks401ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type ListTasksResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	TaskCollection *shared.TaskCollection
	// Unauthenticated
	ListTasks401ApplicationJSONObject *ListTasks401ApplicationJSON
	// Forbidden
	ListTasks403ApplicationJSONObject *ListTasks403ApplicationJSON
}

func (o *ListTasksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListTasksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListTasksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListTasksResponse) GetTaskCollection() *shared.TaskCollection {
	if o == nil {
		return nil
	}
	return o.TaskCollection
}

func (o *ListTasksResponse) GetListTasks401ApplicationJSONObject() *ListTasks401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ListTasks401ApplicationJSONObject
}

func (o *ListTasksResponse) GetListTasks403ApplicationJSONObject() *ListTasks403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ListTasks403ApplicationJSONObject
}
