// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListContractTypesRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *ListContractTypesRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

type ListContractTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ContractTypeCollection *shared.ContractTypeCollection
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListContractTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListContractTypesResponse) GetContractTypeCollection() *shared.ContractTypeCollection {
	if o == nil {
		return nil
	}
	return o.ContractTypeCollection
}

func (o *ListContractTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListContractTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
