// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListOfficesRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *ListOfficesRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

type ListOfficesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	OfficeCollection *shared.OfficeCollection
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListOfficesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListOfficesResponse) GetOfficeCollection() *shared.OfficeCollection {
	if o == nil {
		return nil
	}
	return o.OfficeCollection
}

func (o *ListOfficesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListOfficesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
