// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListLegalEntitiesSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ListLegalEntitiesRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

// ListLegalEntities403ApplicationJSON - Forbidden
type ListLegalEntities403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// ListLegalEntities401ApplicationJSON - Unauthenticated
type ListLegalEntities401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type ListLegalEntitiesResponse struct {
	ContentType string
	// OK
	LegalEntityCollection *shared.LegalEntityCollection
	StatusCode            int
	RawResponse           *http.Response
	// Unauthenticated
	ListLegalEntities401ApplicationJSONObject *ListLegalEntities401ApplicationJSON
	// Forbidden
	ListLegalEntities403ApplicationJSONObject *ListLegalEntities403ApplicationJSON
}
