// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListLegalEntitiesSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *ListLegalEntitiesSecurity) GetOAuth2() string {
	if o == nil {
		return ""
	}
	return o.OAuth2
}

func (o *ListLegalEntitiesSecurity) GetPersonalAccessToken() string {
	if o == nil {
		return ""
	}
	return o.PersonalAccessToken
}

type ListLegalEntitiesRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

func (o *ListLegalEntitiesRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

// ListLegalEntities403ApplicationJSON - Forbidden
type ListLegalEntities403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *ListLegalEntities403ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// ListLegalEntities401ApplicationJSON - Unauthenticated
type ListLegalEntities401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

func (o *ListLegalEntities401ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type ListLegalEntitiesResponse struct {
	ContentType string
	// OK
	LegalEntityCollection *shared.LegalEntityCollection
	StatusCode            int
	RawResponse           *http.Response
	// Unauthenticated
	ListLegalEntities401ApplicationJSONObject *ListLegalEntities401ApplicationJSON
	// Forbidden
	ListLegalEntities403ApplicationJSONObject *ListLegalEntities403ApplicationJSON
}

func (o *ListLegalEntitiesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListLegalEntitiesResponse) GetLegalEntityCollection() *shared.LegalEntityCollection {
	if o == nil {
		return nil
	}
	return o.LegalEntityCollection
}

func (o *ListLegalEntitiesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListLegalEntitiesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListLegalEntitiesResponse) GetListLegalEntities401ApplicationJSONObject() *ListLegalEntities401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ListLegalEntities401ApplicationJSONObject
}

func (o *ListLegalEntitiesResponse) GetListLegalEntities403ApplicationJSONObject() *ListLegalEntities403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ListLegalEntities403ApplicationJSONObject
}
