// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListDepartmentsSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ListDepartmentsRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

// ListDepartments403ApplicationJSON - Forbidden
type ListDepartments403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// ListDepartments401ApplicationJSON - Unauthenticated
type ListDepartments401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type ListDepartmentsResponse struct {
	ContentType string
	// OK
	DepartmentCollection *shared.DepartmentCollection
	StatusCode           int
	RawResponse          *http.Response
	// Unauthenticated
	ListDepartments401ApplicationJSONObject *ListDepartments401ApplicationJSON
	// Forbidden
	ListDepartments403ApplicationJSONObject *ListDepartments403ApplicationJSON
}
