// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListCustomFieldsSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ListCustomFieldsRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
}

// ListCustomFields403ApplicationJSON - Forbidden
type ListCustomFields403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// ListCustomFields401ApplicationJSON - Unauthenticated
type ListCustomFields401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type ListCustomFieldsResponse struct {
	ContentType string
	// OK
	CustomFieldCollection *shared.CustomFieldCollection
	StatusCode            int
	RawResponse           *http.Response
	// Unauthenticated
	ListCustomFields401ApplicationJSONObject *ListCustomFields401ApplicationJSON
	// Forbidden
	ListCustomFields403ApplicationJSONObject *ListCustomFields403ApplicationJSON
}
