// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type ListRelationsSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ListRelationsRequest struct {
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// The page to retrieve
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// Return relations with a certain reference
	Reference *string `queryParam:"style=form,explode=true,name=reference"`
}

// ListRelations403ApplicationJSON - Forbidden
type ListRelations403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// ListRelations401ApplicationJSON - Unauthenticated
type ListRelations401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type ListRelationsResponse struct {
	ContentType string
	// OK
	RelationCollection *shared.RelationCollection
	StatusCode         int
	RawResponse        *http.Response
	// Unauthenticated
	ListRelations401ApplicationJSONObject *ListRelations401ApplicationJSON
	// Forbidden
	ListRelations403ApplicationJSONObject *ListRelations403ApplicationJSON
}
