// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateContractRequest struct {
	ContractWrite *shared.ContractWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the contract
	Contract int64 `pathParam:"style=simple,explode=false,name=contract"`
}

func (o *UpdateContractRequest) GetContractWrite() *shared.ContractWrite {
	if o == nil {
		return nil
	}
	return o.ContractWrite
}

func (o *UpdateContractRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *UpdateContractRequest) GetContract() int64 {
	if o == nil {
		return 0
	}
	return o.Contract
}

// UpdateContractResponseBody - OK
type UpdateContractResponseBody struct {
	Data *shared.ContractRead `json:"data,omitempty"`
}

func (o *UpdateContractResponseBody) GetData() *shared.ContractRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type UpdateContractResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *UpdateContractResponseBody
}

func (o *UpdateContractResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateContractResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateContractResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateContractResponse) GetObject() *UpdateContractResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
