// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateTaskSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UpdateTaskRequest struct {
	TaskUpdate *shared.TaskUpdate `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the task
	Task int64 `pathParam:"style=simple,explode=false,name=task"`
}

type UpdateTask422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// UpdateTask422ApplicationJSON - Invalid data posted
type UpdateTask422ApplicationJSON struct {
	Errors  []UpdateTask422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                              `json:"message,omitempty"`
}

// UpdateTask404ApplicationJSON - Not Found
type UpdateTask404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateTask403ApplicationJSON - Forbidden
type UpdateTask403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateTask401ApplicationJSON - Unauthenticated
type UpdateTask401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateTask200ApplicationJSON - OK
type UpdateTask200ApplicationJSON struct {
	Data *shared.TaskRead `json:"data,omitempty"`
}

type UpdateTaskResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	UpdateTask200ApplicationJSONObject *UpdateTask200ApplicationJSON
	// Unauthenticated
	UpdateTask401ApplicationJSONObject *UpdateTask401ApplicationJSON
	// Forbidden
	UpdateTask403ApplicationJSONObject *UpdateTask403ApplicationJSON
	// Not Found
	UpdateTask404ApplicationJSONObject *UpdateTask404ApplicationJSON
	// Invalid data posted
	UpdateTask422ApplicationJSONObject *UpdateTask422ApplicationJSON
}
