// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateRelationRequest struct {
	RelationWrite *shared.RelationWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the relation
	Relation int64 `pathParam:"style=simple,explode=false,name=relation"`
}

func (o *UpdateRelationRequest) GetRelationWrite() *shared.RelationWrite {
	if o == nil {
		return nil
	}
	return o.RelationWrite
}

func (o *UpdateRelationRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *UpdateRelationRequest) GetRelation() int64 {
	if o == nil {
		return 0
	}
	return o.Relation
}

// UpdateRelationResponseBody - OK
type UpdateRelationResponseBody struct {
	Data *shared.RelationRead `json:"data,omitempty"`
}

func (o *UpdateRelationResponseBody) GetData() *shared.RelationRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type UpdateRelationResponse struct {
	// OK
	TwoHundredApplicationJSONObject *UpdateRelationResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateRelationResponse) GetTwoHundredApplicationJSONObject() *UpdateRelationResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *UpdateRelationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateRelationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateRelationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
