// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateRelationSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UpdateRelationRequest struct {
	RelationWrite *shared.RelationWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the relation
	Relation int64 `pathParam:"style=simple,explode=false,name=relation"`
}

type UpdateRelation422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// UpdateRelation422ApplicationJSON - Invalid data posted
type UpdateRelation422ApplicationJSON struct {
	Errors  []UpdateRelation422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                  `json:"message,omitempty"`
}

// UpdateRelation404ApplicationJSON - Not Found
type UpdateRelation404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateRelation403ApplicationJSON - Forbidden
type UpdateRelation403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateRelation401ApplicationJSON - Unauthenticated
type UpdateRelation401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateRelation200ApplicationJSON - OK
type UpdateRelation200ApplicationJSON struct {
	Data *shared.RelationRead `json:"data,omitempty"`
}

type UpdateRelationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	UpdateRelation200ApplicationJSONObject *UpdateRelation200ApplicationJSON
	// Unauthenticated
	UpdateRelation401ApplicationJSONObject *UpdateRelation401ApplicationJSON
	// Forbidden
	UpdateRelation403ApplicationJSONObject *UpdateRelation403ApplicationJSON
	// Not Found
	UpdateRelation404ApplicationJSONObject *UpdateRelation404ApplicationJSON
	// Invalid data posted
	UpdateRelation422ApplicationJSONObject *UpdateRelation422ApplicationJSON
}
