// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateDocumentRequest struct {
	DocumentWrite *shared.DocumentWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the document
	Document int64 `pathParam:"style=simple,explode=false,name=document"`
}

func (o *UpdateDocumentRequest) GetDocumentWrite() *shared.DocumentWrite {
	if o == nil {
		return nil
	}
	return o.DocumentWrite
}

func (o *UpdateDocumentRequest) GetCompany() int64 {
	if o == nil {
		return 0
	}
	return o.Company
}

func (o *UpdateDocumentRequest) GetDocument() int64 {
	if o == nil {
		return 0
	}
	return o.Document
}

// UpdateDocumentResponseBody - OK
type UpdateDocumentResponseBody struct {
	Data *shared.DocumentRead `json:"data,omitempty"`
}

func (o *UpdateDocumentResponseBody) GetData() *shared.DocumentRead {
	if o == nil {
		return nil
	}
	return o.Data
}

type UpdateDocumentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *UpdateDocumentResponseBody
}

func (o *UpdateDocumentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateDocumentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateDocumentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateDocumentResponse) GetObject() *UpdateDocumentResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
