// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateContractSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UpdateContractRequest struct {
	ContractWrite *shared.ContractWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the contract
	Contract int64 `pathParam:"style=simple,explode=false,name=contract"`
}

type UpdateContract422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// UpdateContract422ApplicationJSON - Invalid data posted
type UpdateContract422ApplicationJSON struct {
	Errors  []UpdateContract422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                  `json:"message,omitempty"`
}

// UpdateContract404ApplicationJSON - Not Found
type UpdateContract404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateContract403ApplicationJSON - Forbidden
type UpdateContract403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateContract401ApplicationJSON - Unauthenticated
type UpdateContract401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateContract200ApplicationJSON - OK
type UpdateContract200ApplicationJSON struct {
	Data *shared.ContractRead `json:"data,omitempty"`
}

type UpdateContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	UpdateContract200ApplicationJSONObject *UpdateContract200ApplicationJSON
	// Unauthenticated
	UpdateContract401ApplicationJSONObject *UpdateContract401ApplicationJSON
	// Forbidden
	UpdateContract403ApplicationJSONObject *UpdateContract403ApplicationJSON
	// Not Found
	UpdateContract404ApplicationJSONObject *UpdateContract404ApplicationJSON
	// Invalid data posted
	UpdateContract422ApplicationJSONObject *UpdateContract422ApplicationJSON
}
