// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateOfficeSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UpdateOfficeRequest struct {
	OfficeWrite *shared.OfficeWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the office
	Office int64 `pathParam:"style=simple,explode=false,name=office"`
}

type UpdateOffice422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// UpdateOffice422ApplicationJSON - Invalid data posted
type UpdateOffice422ApplicationJSON struct {
	Errors  []UpdateOffice422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                `json:"message,omitempty"`
}

// UpdateOffice404ApplicationJSON - Not Found
type UpdateOffice404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateOffice403ApplicationJSON - Forbidden
type UpdateOffice403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateOffice401ApplicationJSON - Unauthenticated
type UpdateOffice401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateOffice200ApplicationJSON - OK
type UpdateOffice200ApplicationJSON struct {
	Data *shared.OfficeRead `json:"data,omitempty"`
}

type UpdateOfficeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	UpdateOffice200ApplicationJSONObject *UpdateOffice200ApplicationJSON
	// Unauthenticated
	UpdateOffice401ApplicationJSONObject *UpdateOffice401ApplicationJSON
	// Forbidden
	UpdateOffice403ApplicationJSONObject *UpdateOffice403ApplicationJSON
	// Not Found
	UpdateOffice404ApplicationJSONObject *UpdateOffice404ApplicationJSON
	// Invalid data posted
	UpdateOffice422ApplicationJSONObject *UpdateOffice422ApplicationJSON
}
