// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"ContractifyProduction/pkg/models/shared"
	"net/http"
)

type UpdateDepartmentSecurity struct {
	OAuth2              string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UpdateDepartmentRequest struct {
	DepartmentWrite *shared.DepartmentWrite `request:"mediaType=application/json"`
	// Id of the company
	Company int64 `pathParam:"style=simple,explode=false,name=company"`
	// Id of the department
	Department int64 `pathParam:"style=simple,explode=false,name=department"`
}

type UpdateDepartment422ApplicationJSONErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

// UpdateDepartment422ApplicationJSON - Invalid data posted
type UpdateDepartment422ApplicationJSON struct {
	Errors  []UpdateDepartment422ApplicationJSONErrors `json:"errors,omitempty"`
	Message *string                                    `json:"message,omitempty"`
}

// UpdateDepartment404ApplicationJSON - Not Found
type UpdateDepartment404ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateDepartment403ApplicationJSON - Forbidden
type UpdateDepartment403ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateDepartment401ApplicationJSON - Unauthenticated
type UpdateDepartment401ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// UpdateDepartment200ApplicationJSON - OK
type UpdateDepartment200ApplicationJSON struct {
	Data *shared.DepartmentRead `json:"data,omitempty"`
}

type UpdateDepartmentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	UpdateDepartment200ApplicationJSONObject *UpdateDepartment200ApplicationJSON
	// Unauthenticated
	UpdateDepartment401ApplicationJSONObject *UpdateDepartment401ApplicationJSON
	// Forbidden
	UpdateDepartment403ApplicationJSONObject *UpdateDepartment403ApplicationJSON
	// Not Found
	UpdateDepartment404ApplicationJSONObject *UpdateDepartment404ApplicationJSON
	// Invalid data posted
	UpdateDepartment422ApplicationJSONObject *UpdateDepartment422ApplicationJSON
}
