// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type CreateOfficeErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

func (o *CreateOfficeErrors) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *CreateOfficeErrors) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

// CreateOfficeOfficesResponseResponseBody - Invalid data posted
type CreateOfficeOfficesResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response       `json:"-"`
	Errors      []CreateOfficeErrors `json:"errors,omitempty"`
	Message     *string              `json:"message,omitempty"`
}

var _ error = &CreateOfficeOfficesResponseResponseBody{}

func (e *CreateOfficeOfficesResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateOfficeOfficesResponseBody - Forbidden
type CreateOfficeOfficesResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CreateOfficeOfficesResponseBody{}

func (e *CreateOfficeOfficesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateOfficeResponseBody - Unauthenticated
type CreateOfficeResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CreateOfficeResponseBody{}

func (e *CreateOfficeResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
