// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type CreateTaskErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

func (o *CreateTaskErrors) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *CreateTaskErrors) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

// CreateTaskTasksResponseResponseBody - Invalid data posted
type CreateTaskTasksResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response     `json:"-"`
	Errors      []CreateTaskErrors `json:"errors,omitempty"`
	Message     *string            `json:"message,omitempty"`
}

var _ error = &CreateTaskTasksResponseResponseBody{}

func (e *CreateTaskTasksResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateTaskTasksResponseBody - Forbidden
type CreateTaskTasksResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CreateTaskTasksResponseBody{}

func (e *CreateTaskTasksResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateTaskResponseBody - Unauthenticated
type CreateTaskResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CreateTaskResponseBody{}

func (e *CreateTaskResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
