// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type Errors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

func (o *Errors) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *Errors) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

// CreateContractContractsResponseResponseBody - Invalid data posted
type CreateContractContractsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Errors      []Errors       `json:"errors,omitempty"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CreateContractContractsResponseResponseBody{}

func (e *CreateContractContractsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateContractContractsResponseBody - Forbidden
type CreateContractContractsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CreateContractContractsResponseBody{}

func (e *CreateContractContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateContractResponseBody - Unauthenticated
type CreateContractResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CreateContractResponseBody{}

func (e *CreateContractResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
