// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// CurrentUserUsersResponseBody - Forbidden
type CurrentUserUsersResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CurrentUserUsersResponseBody{}

func (e *CurrentUserUsersResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CurrentUserResponseBody - Unauthenticated
type CurrentUserResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &CurrentUserResponseBody{}

func (e *CurrentUserResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
