// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// DeleteRelationRelationsResponse404ResponseBody - Not Found
type DeleteRelationRelationsResponse404ResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteRelationRelationsResponse404ResponseBody{}

func (e *DeleteRelationRelationsResponse404ResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteRelationRelationsResponseResponseBody - Forbidden
type DeleteRelationRelationsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteRelationRelationsResponseResponseBody{}

func (e *DeleteRelationRelationsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteRelationRelationsResponseBody - Unauthenticated
type DeleteRelationRelationsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteRelationRelationsResponseBody{}

func (e *DeleteRelationRelationsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteRelationResponseBody - Precondition failed
type DeleteRelationResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteRelationResponseBody{}

func (e *DeleteRelationResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
