// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// DeleteOfficeOfficesResponse404ResponseBody - Not Found
type DeleteOfficeOfficesResponse404ResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteOfficeOfficesResponse404ResponseBody{}

func (e *DeleteOfficeOfficesResponse404ResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteOfficeOfficesResponseResponseBody - Forbidden
type DeleteOfficeOfficesResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteOfficeOfficesResponseResponseBody{}

func (e *DeleteOfficeOfficesResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteOfficeOfficesResponseBody - Unauthenticated
type DeleteOfficeOfficesResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteOfficeOfficesResponseBody{}

func (e *DeleteOfficeOfficesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteOfficeResponseBody - Precondition failed
type DeleteOfficeResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteOfficeResponseBody{}

func (e *DeleteOfficeResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
