// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// DeleteDepartmentDepartmentsResponse404ResponseBody - Not Found
type DeleteDepartmentDepartmentsResponse404ResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteDepartmentDepartmentsResponse404ResponseBody{}

func (e *DeleteDepartmentDepartmentsResponse404ResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteDepartmentDepartmentsResponseResponseBody - Forbidden
type DeleteDepartmentDepartmentsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteDepartmentDepartmentsResponseResponseBody{}

func (e *DeleteDepartmentDepartmentsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteDepartmentDepartmentsResponseBody - Unauthenticated
type DeleteDepartmentDepartmentsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteDepartmentDepartmentsResponseBody{}

func (e *DeleteDepartmentDepartmentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteDepartmentResponseBody - Precondition failed
type DeleteDepartmentResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &DeleteDepartmentResponseBody{}

func (e *DeleteDepartmentResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
