// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// GetDocumentDocumentsResponseResponseBody - Not Found
type GetDocumentDocumentsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetDocumentDocumentsResponseResponseBody{}

func (e *GetDocumentDocumentsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetDocumentDocumentsResponseBody - Forbidden
type GetDocumentDocumentsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetDocumentDocumentsResponseBody{}

func (e *GetDocumentDocumentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetDocumentResponseBody - Unauthenticated
type GetDocumentResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetDocumentResponseBody{}

func (e *GetDocumentResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
