// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// GetDepartmentDepartmentsResponseResponseBody - Not Found
type GetDepartmentDepartmentsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetDepartmentDepartmentsResponseResponseBody{}

func (e *GetDepartmentDepartmentsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetDepartmentDepartmentsResponseBody - Forbidden
type GetDepartmentDepartmentsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetDepartmentDepartmentsResponseBody{}

func (e *GetDepartmentDepartmentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetDepartmentResponseBody - Unauthenticated
type GetDepartmentResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetDepartmentResponseBody{}

func (e *GetDepartmentResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
