// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// GetRelationRelationsResponseResponseBody - Not Found
type GetRelationRelationsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetRelationRelationsResponseResponseBody{}

func (e *GetRelationRelationsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetRelationRelationsResponseBody - Forbidden
type GetRelationRelationsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetRelationRelationsResponseBody{}

func (e *GetRelationRelationsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetRelationResponseBody - Unauthenticated
type GetRelationResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &GetRelationResponseBody{}

func (e *GetRelationResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
