// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// ListDocumentsDocumentsResponseBody - Forbidden
type ListDocumentsDocumentsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListDocumentsDocumentsResponseBody{}

func (e *ListDocumentsDocumentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListDocumentsResponseBody - Unauthenticated
type ListDocumentsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListDocumentsResponseBody{}

func (e *ListDocumentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
