// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// ListOfficesOfficesResponseBody - Forbidden
type ListOfficesOfficesResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListOfficesOfficesResponseBody{}

func (e *ListOfficesOfficesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListOfficesResponseBody - Unauthenticated
type ListOfficesResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListOfficesResponseBody{}

func (e *ListOfficesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
