// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// ListUsersUsersResponseBody - Forbidden
type ListUsersUsersResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListUsersUsersResponseBody{}

func (e *ListUsersUsersResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListUsersResponseBody - Unauthenticated
type ListUsersResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListUsersResponseBody{}

func (e *ListUsersResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
