// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// ListSubfoldersSubfoldersResponseBody - Forbidden
type ListSubfoldersSubfoldersResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListSubfoldersSubfoldersResponseBody{}

func (e *ListSubfoldersSubfoldersResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListSubfoldersResponseBody - Unauthenticated
type ListSubfoldersResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListSubfoldersResponseBody{}

func (e *ListSubfoldersResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
