// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// ListTasksTasksResponseBody - Forbidden
type ListTasksTasksResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListTasksTasksResponseBody{}

func (e *ListTasksTasksResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListTasksResponseBody - Unauthenticated
type ListTasksResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &ListTasksResponseBody{}

func (e *ListTasksResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
