// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type UpdateDepartmentErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

func (o *UpdateDepartmentErrors) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *UpdateDepartmentErrors) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

// UpdateDepartmentDepartmentsResponse422ResponseBody - Invalid data posted
type UpdateDepartmentDepartmentsResponse422ResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response           `json:"-"`
	Errors      []UpdateDepartmentErrors `json:"errors,omitempty"`
	Message     *string                  `json:"message,omitempty"`
}

var _ error = &UpdateDepartmentDepartmentsResponse422ResponseBody{}

func (e *UpdateDepartmentDepartmentsResponse422ResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateDepartmentDepartmentsResponseResponseBody - Not Found
type UpdateDepartmentDepartmentsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateDepartmentDepartmentsResponseResponseBody{}

func (e *UpdateDepartmentDepartmentsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateDepartmentDepartmentsResponseBody - Forbidden
type UpdateDepartmentDepartmentsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateDepartmentDepartmentsResponseBody{}

func (e *UpdateDepartmentDepartmentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateDepartmentResponseBody - Unauthenticated
type UpdateDepartmentResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateDepartmentResponseBody{}

func (e *UpdateDepartmentResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
