// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// UpdateDocumentDocumentsResponseResponseBody - Not Found
type UpdateDocumentDocumentsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateDocumentDocumentsResponseResponseBody{}

func (e *UpdateDocumentDocumentsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateDocumentDocumentsResponseBody - Forbidden
type UpdateDocumentDocumentsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateDocumentDocumentsResponseBody{}

func (e *UpdateDocumentDocumentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateDocumentResponseBody - Unauthenticated
type UpdateDocumentResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateDocumentResponseBody{}

func (e *UpdateDocumentResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
