// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type UpdateContractErrors struct {
	Errors []string `json:"errors,omitempty"`
	Field  *string  `json:"field,omitempty"`
}

func (o *UpdateContractErrors) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *UpdateContractErrors) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

// UpdateContractContractsResponse422ResponseBody - Invalid data posted
type UpdateContractContractsResponse422ResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response         `json:"-"`
	Errors      []UpdateContractErrors `json:"errors,omitempty"`
	Message     *string                `json:"message,omitempty"`
}

var _ error = &UpdateContractContractsResponse422ResponseBody{}

func (e *UpdateContractContractsResponse422ResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateContractContractsResponseResponseBody - Not Found
type UpdateContractContractsResponseResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateContractContractsResponseResponseBody{}

func (e *UpdateContractContractsResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateContractContractsResponseBody - Forbidden
type UpdateContractContractsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateContractContractsResponseBody{}

func (e *UpdateContractContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateContractResponseBody - Unauthenticated
type UpdateContractResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &UpdateContractResponseBody{}

func (e *UpdateContractResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
