// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ContractDocumentRead struct {
	CreatedAt   *time.Time            `json:"created_at,omitempty"`
	Description *string               `json:"description,omitempty"`
	Dossiers    []DossierRead         `json:"dossiers,omitempty"`
	DownloadURL *string               `json:"download_url,omitempty"`
	ID          *int64                `json:"id,omitempty"`
	Name        *string               `json:"name,omitempty"`
	OwnerID     *int64                `json:"owner_id,omitempty"`
	Versions    []DocumentVersionRead `json:"versions,omitempty"`
}
