// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContractTypeNameRead struct {
	En *string `json:"en,omitempty"`
	Fr *string `json:"fr,omitempty"`
	Nl *string `json:"nl,omitempty"`
}
