// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"ContractifyProduction/pkg/types"
)

type ContractTermination struct {
	IsTerminableAtAnyTime *bool       `json:"is_terminable_at_any_time,omitempty"`
	TerminationDate       *types.Date `json:"termination_date,omitempty"`
	TerminationDuration   *string     `json:"termination_duration,omitempty"`
}
