// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContractRenewal struct {
	AutomaticRenewal       *ContractAutomaticRenewal `json:"automatic_renewal,omitempty"`
	IsAutomaticallyRenewed *bool                     `json:"is_automatically_renewed,omitempty"`
}
