// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContractTypeRead struct {
	ID   *int64                `json:"id,omitempty"`
	Name *ContractTypeNameRead `json:"name,omitempty"`
}
