// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"ContractifyProduction/pkg/types"
)

type ContractWrite struct {
	ContractTypes     []int64                 `json:"contract_types,omitempty"`
	CustomFieldValues []CustomFieldValueWrite `json:"custom_field_values,omitempty"`
	Departments       []int64                 `json:"departments,omitempty"`
	Documents         []int64                 `json:"documents,omitempty"`
	DossierID         int64                   `json:"dossier_id"`
	Duration          *string                 `json:"duration,omitempty"`
	EndDate           *types.Date             `json:"end_date,omitempty"`
	IsOpenEnded       *bool                   `json:"is_open_ended,omitempty"`
	LegalEntities     []int64                 `json:"legal_entities,omitempty"`
	Name              string                  `json:"name"`
	Offices           []int64                 `json:"offices,omitempty"`
	OwnerID           *int64                  `json:"owner_id,omitempty"`
	Phase             *ContractPhase          `json:"phase,omitempty"`
	Relations         []int64                 `json:"relations,omitempty"`
	Renewal           *ContractRenewal        `json:"renewal,omitempty"`
	StartDate         *types.Date             `json:"start_date,omitempty"`
	Termination       *ContractTermination    `json:"termination,omitempty"`
}
