// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"ContractifyProduction/pkg/types"
)

type ContractWrite struct {
	ContractTypes     []int64                 `json:"contract_types,omitempty"`
	CustomFieldValues []CustomFieldValueWrite `json:"custom_field_values,omitempty"`
	Departments       []int64                 `json:"departments,omitempty"`
	Documents         []int64                 `json:"documents,omitempty"`
	DossierID         int64                   `json:"dossier_id"`
	Duration          *string                 `json:"duration,omitempty"`
	EndDate           *types.Date             `json:"end_date,omitempty"`
	IsOpenEnded       *bool                   `json:"is_open_ended,omitempty"`
	LegalEntities     []int64                 `json:"legal_entities,omitempty"`
	Name              string                  `json:"name"`
	Offices           []int64                 `json:"offices,omitempty"`
	OwnerID           *int64                  `json:"owner_id,omitempty"`
	Phase             *ContractPhase          `json:"phase,omitempty"`
	Relations         []int64                 `json:"relations,omitempty"`
	Renewal           *ContractRenewal        `json:"renewal,omitempty"`
	StartDate         *types.Date             `json:"start_date,omitempty"`
	Termination       *ContractTermination    `json:"termination,omitempty"`
}

func (o *ContractWrite) GetContractTypes() []int64 {
	if o == nil {
		return nil
	}
	return o.ContractTypes
}

func (o *ContractWrite) GetCustomFieldValues() []CustomFieldValueWrite {
	if o == nil {
		return nil
	}
	return o.CustomFieldValues
}

func (o *ContractWrite) GetDepartments() []int64 {
	if o == nil {
		return nil
	}
	return o.Departments
}

func (o *ContractWrite) GetDocuments() []int64 {
	if o == nil {
		return nil
	}
	return o.Documents
}

func (o *ContractWrite) GetDossierID() int64 {
	if o == nil {
		return 0
	}
	return o.DossierID
}

func (o *ContractWrite) GetDuration() *string {
	if o == nil {
		return nil
	}
	return o.Duration
}

func (o *ContractWrite) GetEndDate() *types.Date {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *ContractWrite) GetIsOpenEnded() *bool {
	if o == nil {
		return nil
	}
	return o.IsOpenEnded
}

func (o *ContractWrite) GetLegalEntities() []int64 {
	if o == nil {
		return nil
	}
	return o.LegalEntities
}

func (o *ContractWrite) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ContractWrite) GetOffices() []int64 {
	if o == nil {
		return nil
	}
	return o.Offices
}

func (o *ContractWrite) GetOwnerID() *int64 {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

func (o *ContractWrite) GetPhase() *ContractPhase {
	if o == nil {
		return nil
	}
	return o.Phase
}

func (o *ContractWrite) GetRelations() []int64 {
	if o == nil {
		return nil
	}
	return o.Relations
}

func (o *ContractWrite) GetRenewal() *ContractRenewal {
	if o == nil {
		return nil
	}
	return o.Renewal
}

func (o *ContractWrite) GetStartDate() *types.Date {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *ContractWrite) GetTermination() *ContractTermination {
	if o == nil {
		return nil
	}
	return o.Termination
}
