// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ContractPhase string

const (
	ContractPhaseTender        ContractPhase = "tender"
	ContractPhaseOngoing       ContractPhase = "ongoing"
	ContractPhaseInTermination ContractPhase = "in_termination"
	ContractPhaseEnded         ContractPhase = "ended"
	ContractPhaseInReview      ContractPhase = "in_review"
)

func (e ContractPhase) ToPointer() *ContractPhase {
	return &e
}

func (e *ContractPhase) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tender":
		fallthrough
	case "ongoing":
		fallthrough
	case "in_termination":
		fallthrough
	case "ended":
		fallthrough
	case "in_review":
		*e = ContractPhase(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContractPhase: %v", v)
	}
}
