// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CustomFieldRead struct {
	ID         *int64  `json:"id,omitempty"`
	IsContract *bool   `json:"is_contract,omitempty"`
	IsDocument *bool   `json:"is_document,omitempty"`
	Name       *string `json:"name,omitempty"`
	Type       *string `json:"type,omitempty"`
}
