// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CustomFieldCollection - OK
type CustomFieldCollection struct {
	Data []CustomFieldRead `json:"data,omitempty"`
	Meta *Pagination       `json:"meta,omitempty"`
}
