// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CustomFieldValueWrite struct {
	CustomFieldID *int64      `json:"custom_field_id,omitempty"`
	Value         interface{} `json:"value,omitempty"`
}
