// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CustomFieldRead struct {
	ID         *int64  `json:"id,omitempty"`
	IsContract *bool   `json:"is_contract,omitempty"`
	IsDocument *bool   `json:"is_document,omitempty"`
	Name       *string `json:"name,omitempty"`
	Type       *string `json:"type,omitempty"`
}

func (o *CustomFieldRead) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CustomFieldRead) GetIsContract() *bool {
	if o == nil {
		return nil
	}
	return o.IsContract
}

func (o *CustomFieldRead) GetIsDocument() *bool {
	if o == nil {
		return nil
	}
	return o.IsDocument
}

func (o *CustomFieldRead) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CustomFieldRead) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
