// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DepartmentCollection struct {
	Data []DepartmentRead `json:"data,omitempty"`
}

func (o *DepartmentCollection) GetData() []DepartmentRead {
	if o == nil {
		return nil
	}
	return o.Data
}
