// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DepartmentRead struct {
	ID        *int64  `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	Permalink *string `json:"permalink,omitempty"`
}

func (o *DepartmentRead) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *DepartmentRead) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DepartmentRead) GetPermalink() *string {
	if o == nil {
		return nil
	}
	return o.Permalink
}
