// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DepartmentCollection - OK
type DepartmentCollection struct {
	Data []DepartmentRead `json:"data,omitempty"`
}
