// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DepartmentRead struct {
	ID        *int64  `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	Permalink *string `json:"permalink,omitempty"`
}
