// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DocumentCollection - OK
type DocumentCollection struct {
	Data []DocumentRead `json:"data,omitempty"`
	Meta *Pagination    `json:"meta,omitempty"`
}

func (o *DocumentCollection) GetData() []DocumentRead {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *DocumentCollection) GetMeta() *Pagination {
	if o == nil {
		return nil
	}
	return o.Meta
}
