// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DocumentVersionRead struct {
	CreatedAt        *string `json:"created_at,omitempty"`
	DetectedLanugage *string `json:"detected_lanugage,omitempty"`
	DownloadURL      *string `json:"download_url,omitempty"`
	FileSize         *int64  `json:"file_size,omitempty"`
	FileType         *string `json:"file_type,omitempty"`
	MimeType         *string `json:"mime_type,omitempty"`
	Name             *string `json:"name,omitempty"`
}
