// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DocumentWrite struct {
	Contracts         []int64                 `json:"contracts,omitempty"`
	CustomFieldValues []CustomFieldValueWrite `json:"custom_field_values,omitempty"`
	Description       *string                 `json:"description,omitempty"`
	Dossiers          []int64                 `json:"dossiers,omitempty"`
	Name              string                  `json:"name"`
	OwnerID           *int64                  `json:"owner_id,omitempty"`
}
