// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DossierCollection - OK
type DossierCollection struct {
	Data []DossierRead `json:"data,omitempty"`
	Meta *Pagination   `json:"meta,omitempty"`
}
