// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LegalEntityRead struct {
	Bus     *string `json:"bus,omitempty"`
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
	ID      *int64  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Street  *string `json:"street,omitempty"`
	Vat     *string `json:"vat,omitempty"`
	Zip     *string `json:"zip,omitempty"`
}

func (o *LegalEntityRead) GetBus() *string {
	if o == nil {
		return nil
	}
	return o.Bus
}

func (o *LegalEntityRead) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *LegalEntityRead) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *LegalEntityRead) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *LegalEntityRead) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *LegalEntityRead) GetStreet() *string {
	if o == nil {
		return nil
	}
	return o.Street
}

func (o *LegalEntityRead) GetVat() *string {
	if o == nil {
		return nil
	}
	return o.Vat
}

func (o *LegalEntityRead) GetZip() *string {
	if o == nil {
		return nil
	}
	return o.Zip
}
