// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LegalEntityRead struct {
	Bus     *string `json:"bus,omitempty"`
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
	ID      *int64  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Street  *string `json:"street,omitempty"`
	Vat     *string `json:"vat,omitempty"`
	Zip     *string `json:"zip,omitempty"`
}
