// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfficeRead struct {
	Bus            *string `json:"bus,omitempty"`
	City           *string `json:"city,omitempty"`
	ContactPerson  *string `json:"contact_person,omitempty"`
	Country        *string `json:"country,omitempty"`
	Email          *string `json:"email,omitempty"`
	ID             *int64  `json:"id,omitempty"`
	Name           *string `json:"name,omitempty"`
	NumberIdentity *string `json:"number_identity,omitempty"`
	Permalink      *string `json:"permalink,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	Street         *string `json:"street,omitempty"`
	Zip            *string `json:"zip,omitempty"`
}
