// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RelationCollection - OK
type RelationCollection struct {
	Data []RelationRead `json:"data,omitempty"`
	Meta *Pagination    `json:"meta,omitempty"`
}

func (o *RelationCollection) GetData() []RelationRead {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *RelationCollection) GetMeta() *Pagination {
	if o == nil {
		return nil
	}
	return o.Meta
}
