// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RelationWrite struct {
	Address     *Address `json:"address,omitempty"`
	Email       *string  `json:"email,omitempty"`
	Fax         *string  `json:"fax,omitempty"`
	MobilePhone *string  `json:"mobile_phone,omitempty"`
	Name        string   `json:"name"`
	Phone       *string  `json:"phone,omitempty"`
	Reference   *string  `json:"reference,omitempty"`
	Vat         *string  `json:"vat,omitempty"`
	Website     *string  `json:"website,omitempty"`
}
