// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RelationCollection - OK
type RelationCollection struct {
	Data []RelationRead `json:"data,omitempty"`
	Meta *Pagination    `json:"meta,omitempty"`
}
