// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type UserCurrent struct {
	CompaniesWhereAdmin []CompanyRead `json:"companies_where_admin,omitempty"`
	CreatedAt           *time.Time    `json:"created_at,omitempty"`
	Email               *string       `json:"email,omitempty"`
	ID                  *int64        `json:"id,omitempty"`
	Name                *string       `json:"name,omitempty"`
}
